### ISSUE TITLE
Getting errors with jest - nanomatch issue?

### ISSUE THREAD

**Issue by jwulf** [micromatch/nanomatch#14]
_(Thanks for reporting an issue to nanomatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
Run jest with the latest version
…

## What is happening (but shouldn't):
```
TypeError: Cannot read property 'addQmark' of undefined
    at Compiler.<anonymous> (/Users/my-user/.config/yarn/global/node_modules/nanomatch/lib/compilers.js:92:16)
    at Compiler.visit (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/Users/my-user/.config/yarn/global/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/Users/my-user/.config/yarn/global/node_modules/snapdragon/index.js:156:32)
    at /Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:786:23
    at memoize (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:783:10)
    at create (/Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:686:25)
    at /Users/my-user/.config/yarn/global/node_modules/micromatch/index.js:695:16
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/my-user/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)```
```
…

## What should be happening instead?
jest should run the tests
…

**Comment by jonschlinkert** [comment]
So, if I pull down jest directly and run the jest unit tests, it will reproduce this issue? 

It looks like you're not running jest directly. (edit: does jest run yeoman? I'll pull it down and check for myself, it just threw me off)

**Comment by shepherdwind** [comment]
I have the some problem now. The old version 1.2.9 run ok.

**Comment by jonschlinkert** [comment]
Ok, I'm going to temporarily revert the latest until I get this figured out. thanks for reporting.

**Comment by jonschlinkert** [comment]
done. please try deleting node_modules, then reinstall everything to see if that fixes the problem.

**Comment by a-brun** [comment]
Runs good for me now. Thanks!

**Comment by jonschlinkert** [comment]
thanks! I'm going to close to continue the conversation on https://github.com/micromatch/nanomatch/issues/15

**Comment by shepherdwind** [comment]
I try to print the `node` object and result output is `{ type: 'slash', val: '/' }`. So the new version `prev` equal `undefined`. 

https://github.com/micromatch/nanomatch/blob/a983ca01207f0e01a5ef5368aa9bd60e882135e9/lib/compilers.js#L92-L94

**Comment by jonschlinkert** [comment]
> try to print the node object and result output is { type: 'slash', val: '/' }. So the new version prev equal undefined.

perfect,  I suspected it was related to that, thanks for the debugging. that helps
