### ISSUE TITLE
v1.2.11 breaks micromatch

### ISSUE THREAD

**Issue by gera2ld** [micromatch/nanomatch#15]
_(Thanks for reporting an issue to nanomatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

```sh
$ yarn add micromatch
$ node
> console.log(require('micromatch')(['foo', 'bar', 'qux'], ['f*', 'b*']));
```

## What is happening (but shouldn't):
```
TypeError: Cannot read property 'prev' of undefined
    at Compiler.<anonymous> (~/node_modules/nanomatch/lib/compilers.js:267:24)
```

## What should be happening instead?

After downgrading nanomatch to v1.2.9, it works as below:
```
> console.log(require('micromatch')(['foo', 'bar', 'qux'], ['f*', 'b*']));
[ 'foo', 'bar' ]
```

**Comment by jonschlinkert** [comment]
thanks for reporting. I reverted the patch, but I'll keep this open until I figure out specifically which thing I did that broke micromatch.

**Comment by thejollyrogers** [comment]
Also received an error:
```
TypeError: Cannot read property 'addQmark' of undefined
    at Compiler.<anonymous> (/app/node_modules/nanomatch/lib/compilers.js:92:16)
```

**Comment by jonschlinkert** [comment]
I figured it out, it was a bonehead move on my part. Since it's been a couple of months, I completely forgot that the underlying parser was upgraded in nanomatch, but not in micromatch. Since I locally started upgrading the parser in micromatch I didn't see the failures when I tested the nanomatch changes in micromatch. 

Sorry for the inconvenience, and thank you for helping me track down the bugs.

**Comment by thejollyrogers** [comment]
Thanks for the timely update and communication!

**Comment by jek-bao-choo** [comment]
This issue affected Firebase Cloud Functions https://stackoverflow.com/questions/51055137/firebase-functions-for-firestore-failing-due-to-nanomatch-issue

**Comment by jonschlinkert** [comment]
Thanks @choopage, I made comments there to re-direct the conversation here.

**Comment by vijayasri5G4** [comment]
i deleted the node _modules and reinstall it using the command npm install. and deployed my functions  but again i am facing same problem.

**Comment by jonschlinkert** [comment]
> i deleted the node _modules and reinstall it using the command npm install. and deployed my functions but again i am facing same problem.

Then a cached version of nanomatch is probably being used. You might need to delete lockfiles too. Where are the errors happening? Locally? Somewhere else? I'll need more info to help you debug.

**Comment by vijayasri5G4** [comment]
where do i found lock files ?

**Comment by dew0** [comment]
Same problem here (using Firebase Cloud Functions, reinstall doesn't seem to do anything). Perhaps Google themselves need to reinstall to pick up the fixed version? (it fails on running a cloud function, no problems locally or when deploying cloud functions)

**Comment by EvgenyAGM** [comment]
As a firebase functions users I never installed nanomatch intentionally, but it looks like it's a part of firebase-admin tools...

**Comment by EvgenyAGM** [comment]
It looks like firebase-admin updated itself to broken version and we can't do anything until google updates it :(

**Comment by jonschlinkert** [comment]
> It looks like firebase-admin updated itself to broken version and we can't do anything until google updates it :(

Do you know where we can create an issue about it?

**Comment by mizutori** [comment]
https://github.com/firebase/firebase-tools/issues/274

In the link above a guy in Firebase says, 
```
The Firebase CLI executes your code locally in order to parse the triggers, so you must have node_modules locally in order to deploy. However, when we pack up the functions directory to upload we ignore node_modules so whether it's there or not will not impact deploy time.
```
So I guess updating modules on our part doesn't fix the issue, but it is they who needs to update the modules.

**Comment by wsmlby** [comment]
@jonschlinkert  can you comment on the stackoverflow page? the bug is not actually fixed in firebase and your comment is kind of misleading.

**Comment by dew0** [comment]
For what it's worth, I deleted lock files as well... still no luck of course... as mizutori mentioned above, the node_modules doesn't get uploaded anyway. Seems it needs to be updated server-side at Google. This is probably going to become a pretty big deal...

**Comment by boolai** [comment]
I am having the same problem as well. It is happening when I called stripe api create subscriptions then try and update firestore document.

**Comment by jonschlinkert** [comment]
> can you comment on the stackoverflow page? the bug is not actually fixed in firebase and your comment is kind of misleading.

I did, before you made your comment.

**Comment by dew0** [comment]
Yes, "Firebase Functions for Firestore Failing due to NanoMatch" isn't actually fixed yet (even though nanomatch might be)...

**Comment by jonschlinkert** [comment]
Wait, I think if I just push up another patch it should trigger rebuilds....

**Comment by gkabule** [comment]
i am calling an https cloud function to access firestore from a C# client - and i am getting this response back  - TypeError: Cannot read property 'addQmark' of undefined...  

Anybody figure out the solution or are waiting on Google to fix (panic!)

**Comment by mizutori** [comment]
Seems it's working now!

**Comment by gkabule** [comment]
thanks

**Comment by sharanan** [comment]
The [issue](https://github.com/firebase/firebase-admin-node/issues/298) persists. +1 to problem being at the gcloud's end. Have tried fresh npm install, removing lock files, downgrading firebase-admin, firebase-fn versions.  Still no luck. Anyone else other than @mizutori seeing a happy path? Any workaround while Firebase/GCloud responds?

**Comment by jonschlinkert** [comment]
Earlier, I started getting issues within a few minutes of publishing the broken code, which means it was picked up immediately. Obviously the fact that I unpublished the broken code wasn't picked up. 

Maybe if I re-publish the 1.2.9 release (the working, older code) it will be picked up again?

**Comment by sharanan** [comment]
Gave it another try...its working now!
On local:-
- Remove node_modules, package-lock.json
- Deploy function

**Comment by roger199585** [comment]
It seems that v1.2.11 still have the same problem on my cloud functions.
Any way can solve this problem? Should I install the v1.2.9?

**Comment by jonschlinkert** [comment]
> Should I install the v1.2.9?

Please read this entire thread.

**Comment by dew0** [comment]
I did as sharanan said, and it finally works for me too :)

**Comment by lukashavrlant** [comment]
Can you maybe release a new version of nanomatch with reverted changes instead of unpublishing the existing modules? We still get the error because the nanomatch@1.2.11 is cached somewhere. I certainly can flush all the caches in the way but I think releasing a new version would be a cleaner way to (temporarily) fix it.

**Comment by jonschlinkert** [comment]
> Can you maybe release a new version of nanomatch with reverted changes instead of unpublishing the existing modules?

I didn't unpublish modules, I rolled back a release. I agree though, I'll publish a new patch in a few min. 

edit: done, I re-published 1.2.9 as patch 1.2.13 (the intermediate versions were rolled back). Again, sorry about the issues.

**Comment by mgroenhoff** [comment]
@jonschlinkert Just for my information. If you did not unpublish it, how did you rolled it back?

**Comment by es128** [comment]
@mgroenhoff he unpublished the bad version, not the entire module. Just a semantic issue with the way the question was posed.

**Comment by DevelopCodeUser** [comment]
Thks u!!!!!!! U've saved me!!

**Comment by bruceauyeung** [comment]
looks like the problem still exists within version 1.2.13
